Repository djibal/innersource, pull requests merged in 2021-07, with the labels that each got.

#37 Rename README.markdown to README.md
  README.markdown
Labels: Discoverable-repository, bug, documentation, enhancement, good first issue, help wanted, workflow action builder file

#40 secure this request pull functionality and resolve conflicts encountered during processing
  README.md
Labels: Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, workflow action builder file

#41 Update and remove duplicate files
  workflows/README.md
Labels: Discoverable-repository, Label preview, documentation, duplicate, enhancement, good first issue, help wanted, workflow action builder file

#44 Update and improve by removing in duplicate phrases or blobs
  README.markdown
Labels: Discoverable-repository, Label preview, bug, duplicate, enhancement, workflow action builder file

#50 Update README. and adds structure to improve on sentence to better reads mode
  README.markdown
Labels: Comment-active-scoping-n

#51 Troubleshoot in for issues and fix bugs
  README.markdown
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, workflow action builder file

#47 Create innersource.md and add some git feature for this request
  README.markdown
  innersource.md
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, workflow action builder file

#52 Pull an open Troubleshoot improvement for current repository to upgrade forwards
  .github/workflows/blank.yml
  LICENSE
  README.markdown
  README.md
  _config.yml
  innersource.md
  metrics/README.md
  projects/README.md
  templates/README.md
  templates/atom-bug.md
  templates/atom-feature.md
  templates/github-bug.md
  templates/github-feature.md
  workflows/README.md
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, workflow action builder file

#60 Update project open-source
  innersource.md
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, enhancement, workflow action builder file

#61 Upgrade resources for issue and repository templates
  README.markdown
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, workflow action builder file

#65 Pull Merge feature to reach the better changes
  README.markdown
  README.md
  _config.yml
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, workflow action builder file

#70 Merge features pull into README.markdown to fixed and organized -A
  README.markdown
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, documentation, duplicate, enhancement, good first issue, help wanted, invalid, question, wontfix, workflow action builder file

#72 Merge feature request to fixed-in typos
  README.md
Labels: Comment-active-scoping-n, Discoverable-repository, Label preview, bug, enhancement, workflow action builder file

#74 Create security.md
  SECURITY.md
Labels: Discoverable-repository, bug, workflow action builder file
